version: "2.1"

services:
  rabbitmq:
    image: rabbitmq
    environment:
      - "RABBITMQ_DEFAULT_USER=sensu"
      - "RABBITMQ_DEFAULT_PASS=sensu"
      - "RABBITMQ_DEFAULT_VHOST=/sensu"
    ports:
      - 5672:5672
    expose:
      - 5672
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379 
    restart: always

  sensu-server:
    build: ./sensu/server 
    links:
      - rabbitmq
      - redis
    restart: always

  sensu-api:
    build: ./sensu/api
    links:
      - rabbitmq
      - redis
    restart: always

  uchiwa:
    image: uchiwa/uchiwa
    ports:
      - "3060:3000"
    volumes:
      - "./uchiwa/uchiwa.json:/config/config.json:ro"
    depends_on:
      - sensu-server
      - sensu-api
