version: "2.1"

services:
  rabbitmq:
    image: rabbitmq
    environment:
      - "RABBITMQ_DEFAULT_USER=sensu"
      - "RABBITMQ_DEFAULT_PASS=sensu"
      - "RABBITMQ_DEFAULT_VHOST=/sensu"
    ports:
      - 5672:5672
    expose:
      - 5672
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379 
    restart: always

  sensu-base:
    build: ./sensu/base
    image: sensu-base:latest

  sensu-server:
    build: ./sensu/server 
    depends_on:
      - sensu-base
    links:
      - rabbitmq
      - redis
    volumes:
      - ./openstack/sensu-checks.json:/etc/sensu/conf.d/sensu-checks.json:ro
      - ./openstack/sensu-haproxy-check.json:/etc/sensu/conf.d/sensu-haproxy-check.json:ro
    restart: always

  sensu-api:
    build: ./sensu/api
    depends_on:
      - sensu-base
    links:
      - rabbitmq
      - redis
    restart: always

  uchiwa:
    image: uchiwa/uchiwa
    ports:
      - "3000:3000"
    volumes:
      - "./uchiwa/uchiwa.json:/config/config.json:ro"
    depends_on:
      - sensu-server
      - sensu-api
