version: "2.1"

services:
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - graphite-data:/opt/graphite/storage
      - "./graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf:ro"
      - "./graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf:ro"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - "./grafana/conf/datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro"
    depends_on:
      - graphite
    environment:
      GRAFANA_PLUGIN_LIST: "grafana-piechart-panel"
      FORCE_HOSTNAME: auto
      GRAFANA_USER: admin
      GRAFANA_PASS: admin

volumes:
  graphite-data:
    driver: local
  grafana:
    driver: local
